conda-forge/libnetcdf-feedstock

- recipe/CMakeLists.patch
- recipe/meta.yaml
A few CVEs were reported and fixed in hdf5 back in November 2016: http://blog.talosintelligence.com/2016/11/hdf5-vulns.html
The hdf5 release notes for that release are available here: https://support.hdfgroup.org/ftp/HDF5/current18/src/hdf5-1.8.18-RELEASE.txt
For additional info, please see: https://github.com/conda-forge/hdf5-feedstock/pull/68 and https://github.com/conda-forge/hdf5-feedstock/issues/71
> Upgrade to hdf5 1.8.18

- recipe/build.sh
- recipe/meta.yaml
I don't believe the patch from #18 is working for all URLs and Windows still suffers from poor OPeNDAP support :unamused:
> DO NOT MERGE!!! add a failing test

- appveyor.yml
- recipe/build.sh
- recipe/dap.patch
- recipe/dfile.c.patch
- recipe/dim.c.patch
- recipe/meta.yaml
- recipe/semantics.c.patch
@rsignell-usgs this should solve your Windows `curl` issue and backport the https://github.com/Unidata/netcdf-c/pull/573 fix for the  `4.4.1.1`, which is the only one that works to build Python 2.7 extensions.
> Build 4.4.1.1 with patches

- recipe/build.sh
- recipe/meta.yaml
@czender I'm disabling the hdf4 tests b/c it seems we won't get a new releases of netcdf-c anytime soon.
I don't like disabling failing tests bur hdf4 is a niche feature nowadays and we can recommend people to downgrade to the previous version until a new one is released in case this is actually broken.
> Update to 4.6.1

- recipe/build.sh
- recipe/meta.yaml
The nc-config template combines CMAKE_INSTALL_PREFIX with
CMAKE_INSTALL_LIBDIR when generating paths.  This requires that
CMAKE_INSTALL_LIBDIR be relative to CMAKE_INSTALL_PREFIX
closes #57
> use relative path in CMAKE_INSTALL_LIBDIR

- .ci_support/win_c_compilervs2015vc14.yaml
- .gitattributes
- .github/CODEOWNERS
- README.md
- recipe/meta.yaml
- recipe/patches/0009-include-ncexternl-h.patch
This file is imported in netcdf_par.h and is needed by parallel builds of netcdf4 (see conda-forge/netcdf4-feedstock#95)
Checklist
> Patch to install ncexternl.h in v 4.7.1

- recipe/meta.yaml
This file is imported in netcdf_par.h and is needed by parallel builds of netcdf4 (see https://github.com/conda-forge/netcdf4-feedstock/pull/95)
Checklist
> Patch to install ncexternl.h in v 4.7.2

- recipe/meta.yaml
Upstream does not promise SEMVER and this is the second time micro release broken backwards compatibility. So let's put a tighter pin here to be on the safe side.
Ping @beckermr
> stricter pin due to upstream breakage

- .azure-pipelines/azure-pipelines-osx.yml
- .azure-pipelines/azure-pipelines-win.yml
- .scripts/run_docker_build.sh
- recipe/bld.bat
- recipe/build.sh
- recipe/meta.yaml
Dont path manually lib paths, let CMAKE_PREFIX_PATH do its job.
Manually setting lib paths with wrong slashes prevented the automatic replace for windows.
Closes #101 
@conda-forge-admin please rerender
> Use CMAKE_PREFIX_PATH

- recipe/bld.bat
- recipe/meta.yaml
try to work around https://github.com/Unidata/netcdf-c/issues/1444
we manually pass hdf5 variables to avoid the find_package path which results in target names being added to cmake target config files instead of actual library paths.
> Workaround broken cmake config file

- recipe/build.sh
- recipe/meta.yaml
We can replace sysroot (linux) or xcode (osx) paths by only the lib name, cmake will do the rest.
Closes #110
> Avoid hard-coding paths in cmake config files

- .ci_support/linux_64_mpimpich.yaml
- .ci_support/linux_64_mpinompi.yaml
- .ci_support/linux_64_mpiopenmpi.yaml
- .ci_support/linux_aarch64_mpimpich.yaml
- .ci_support/linux_aarch64_mpinompi.yaml
- .ci_support/linux_aarch64_mpiopenmpi.yaml
- .ci_support/linux_ppc64le_mpimpich.yaml
- .ci_support/linux_ppc64le_mpinompi.yaml
- .ci_support/linux_ppc64le_mpiopenmpi.yaml
- .ci_support/osx_64_mpimpich.yaml
- .ci_support/osx_64_mpinompi.yaml
- .ci_support/osx_64_mpiopenmpi.yaml
- .ci_support/win_64_.yaml
- .scripts/build_steps.sh
- .scripts/logging_utils.sh
- .scripts/run_docker_build.sh
- .scripts/run_osx_build.sh
- README.md
- recipe/bld.bat
- recipe/build.sh
- recipe/meta.yaml
[According to the docs](https://www.unidata.ucar.edu/software/netcdf/documentation/NUG/nczarr_head.html#nczarr_cmake) the defaults are:
```
The necessary CMake flags are as follows (with defaults)
-DENABLE_NCZARR=on – equivalent to the Automake –enable-nczarr option.
-DENABLE_NCZARR_S3=off – equivalent to the Automake –enable-nczarr-s3 option.
-DENABLE_NCZARR_S3_TESTS=off – equivalent to the Automake –enable-nczarr-s3-tests option.
```
I added those anyway to see if we can enable the feature. I'll turn the test on in the next commits.
> zarr support

- .azure-pipelines/azure-pipelines-osx.yml
- README.md
- recipe/meta.yaml
Hi! This is the friendly automated conda-forge-webservice.
I've rerendered the recipe as instructed in #143.
Here's a checklist to do before merging.
> Use more run exports to avoid pulling in static libraries

- .github/CODEOWNERS
- recipe/meta.yaml
Hi! This is the friendly automated conda-forge-webservice.
I've added user @WardF as instructed in #150.
Merge this PR to add the user. Please do not rerender this PR or change it in any way. It has `[ci skip]` in the commit message to avoid pushing a new build and so the build configuration in the feedstock should not be changed.
Please contact [conda-forge/core](https://conda-forge.org/docs/maintainer/maintainer_faq.html#mfaq-contact-core) to have this PR merged, if the maintainer is unresponsive.
Fixes #150
> [ci skip] adding user @WardF

- recipe/build.sh
- recipe/meta.yaml
Checklist
* [👋] Ensured the license file is being packaged.
---
Similar to #155, there's an extra file, `libm.tdb`, listed in the CMAKE_INTERFACE_LIBRARIES section of `netCDFTargets.cmake`. This leads to the following error when building against a library (eg gdal) which depends on netcdf4 from the feedstock:
```
[ 91%] Built target gcore_mdreader
make[2]: *** No rule to make target `/Applications/Xcode_13.2.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.0.sdk/usr/lib/libm.tbd', needed by `libgdal.32.3.6.3.dylib'.  Stop.
```
> Also remove .tbd file from CMake target file on macOS

- recipe/build.sh
- recipe/meta.yaml
Demo (on Linux...)
```
$ echo /Applications/Xcode_13.2.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk/usr/lib/libpthread.dylib | sed -E "s#/Applications/Xcode_[0-9]*.[0-9]*.[0-9]*.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX[0-9]*.[0-9]*.sdk/usr/lib/lib([a-zA-Z0-9]*).(dylib|tbd)#\1#g"
pthread
$ echo /Applications/Xcode_13.2.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk/usr/lib/libpthread.tbd | sed -E "s#/Applications/Xcode_[0-9]*.[0-9]*.[0-9]*.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX[0-9]*.[0-9]*.sdk/usr/lib/lib([a-zA-Z0-9]*).(dylib|tbd)#\1#g"
pthread
```
Checklist
closes #170
>  Fix stripping of OSX libraries in CMake target files (fixes #170) 

- .ci_support/linux_64_mpimpich.yaml
- .ci_support/linux_64_mpinompi.yaml
- .ci_support/linux_64_mpiopenmpi.yaml
- .ci_support/linux_aarch64_mpimpich.yaml
- .ci_support/linux_aarch64_mpinompi.yaml
- .ci_support/linux_aarch64_mpiopenmpi.yaml
- .ci_support/linux_ppc64le_mpimpich.yaml
- .ci_support/linux_ppc64le_mpinompi.yaml
- .ci_support/linux_ppc64le_mpiopenmpi.yaml
- .ci_support/osx_64_mpimpich.yaml
- .ci_support/osx_64_mpinompi.yaml
- .ci_support/osx_64_mpiopenmpi.yaml
- .ci_support/osx_arm64_mpimpich.yaml
- .ci_support/osx_arm64_mpinompi.yaml
- .ci_support/osx_arm64_mpiopenmpi.yaml
- .ci_support/win_64_.yaml
- .github/CODEOWNERS
- README.md
- recipe/build.sh
- recipe/meta.yaml
- recipe/patches/0001-Fix-issue-2674.patch
Checklist
This hopefully fixes the issue of overly abundant HDF5-DIAG messages that has plagued a number of downstream projects.
> Backport fix for Unidata/netcdf-c#2674

- .ci_support/linux_64_mpimpich.yaml
- .ci_support/linux_64_mpinompi.yaml
- .ci_support/linux_64_mpiopenmpi.yaml
- .ci_support/linux_aarch64_mpimpich.yaml
- .ci_support/linux_aarch64_mpinompi.yaml
- .ci_support/linux_aarch64_mpiopenmpi.yaml
- .ci_support/linux_ppc64le_mpimpich.yaml
- .ci_support/linux_ppc64le_mpinompi.yaml
- .ci_support/linux_ppc64le_mpiopenmpi.yaml
- .ci_support/osx_64_mpimpich.yaml
- .ci_support/osx_64_mpinompi.yaml
- .ci_support/osx_64_mpiopenmpi.yaml
- .ci_support/osx_arm64_mpimpich.yaml
- .ci_support/osx_arm64_mpinompi.yaml
- .ci_support/osx_arm64_mpiopenmpi.yaml
- .ci_support/win_64_.yaml
- recipe/bld.bat
- recipe/build.sh
- recipe/meta.yaml
Checklist
This is a straight-up port of @djhoese's PR to add S3 support, rebased onto the latest `main`.
> Add S3 support

- .ci_support/linux_64_mpimpich.yaml
- .ci_support/linux_64_mpinompi.yaml
- .ci_support/linux_64_mpiopenmpi.yaml
- .ci_support/linux_aarch64_mpimpich.yaml
- .ci_support/linux_aarch64_mpinompi.yaml
- .ci_support/linux_aarch64_mpiopenmpi.yaml
- .ci_support/linux_ppc64le_mpimpich.yaml
- .ci_support/linux_ppc64le_mpinompi.yaml
- .ci_support/linux_ppc64le_mpiopenmpi.yaml
- .ci_support/osx_64_mpimpich.yaml
- .ci_support/osx_64_mpinompi.yaml
- .ci_support/osx_64_mpiopenmpi.yaml
- .ci_support/osx_arm64_mpimpich.yaml
- .ci_support/osx_arm64_mpinompi.yaml
- .ci_support/osx_arm64_mpiopenmpi.yaml
- .ci_support/win_64_.yaml
- recipe/bld.bat
- recipe/build.sh
- recipe/meta.yaml
Checklist
*  Reset the build number to `0` (if the version changed)
Reverts S3 support added in #180 in hopes of helping #182 until a permanent fix can be found.
> Revert S3 Support

- recipe/meta.yaml
- recipe/patches/fix-s3-support.patch
This grabs Unidata/netcdf-c#3164 to fix accessing some S3 data. For instance, the following errors on conda-forge currently with 4.9.3, but worked with 4.9.2:
```sh
ncdump -h https://noaa-goes19.s3.amazonaws.com/ABI-L1b-RadC/2025/247/20/OR_ABI-L1b-RadC-M6C02_G19_s20252472016172_e20252472018545_c20252472018578.nc#mode=bytes
```
with the message:
```
ncdump: https://noaa-goes19.s3.amazonaws.com/ABI-L1b-RadC/2025/247/20/OR_ABI-L1b-RadC-M6C02_G19_s20252472016172_e20252472018545_c20252472018578.nc#mode=bytes: NetCDF: S3 error
```
Checklist
> Fix error accessing data on S3
